### ISSUE TITLE
License Missing from Repository.

### ISSUE THREAD

**Issue by melvin2001** [lockfale/DC30_Malicious_Containers_Workshop#2]
please add the standard license to this repo:

BEER-Ware License (Revision 34) – No Dennis Kuntz Open Source License

Copyright (c) 2017 lockFALE lockfale@gmail.com

As long as you email funny stories to us, you can do whatever you want 
with this stuff. Unless you are Dennis Kuntz. Under no circumstances 
shall Dennis Kuntz be granted use of this software, source code, 
documentation or other related material. Persons dealing in the 
Software agree not to knowingly distribute these materials or any 
derivative works to Dennis Kuntz.

-- lockfale@gmail.com didn't write this file.

**Comment by 5stars217** [comment]
[Fixed. ](https://github.com/lockfale/Malicious_Containers_Workshop/commit/f83a5ee35d7c6a8e0419625f2af67c9e29582282)thank you for bringing this to our attention.

**Comment by digital-shokunin** [comment]
Whew, to think that Dennis Kuntz almost could have taken our workshop...
